name: CI/CD

on:  # Trigger this workflow manually
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_on_azure:
    name: Deploy on Azure
    runs-on: ubuntu-latest
    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Checkout repository"
        uses: actions/checkout@main
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          # resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./bicep/main.bicep
          parameters: ./bicep/main.bicepparam
          failOnStdErr: false
          

