name: Deploy

on:  # Trigger this workflow manually
  workflow_dispatch:
    inputs:
      application:
        description: 'Application Workload'
        required: true
        default: 'record-store'
      sql_server_admin_username:
        description: 'Admin Username for SQL server'
        required: true
        default: 'dbadmin'
      sql_server_admin_password: 
        description: 'Admin Password for SQL server'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  set_action_secrets:
    name: Set Action Secrets for SQL admin credentials
    runs-on: ubuntu-latest
    steps:
    - name: Set SQL Admin Username
      uses: jairandresdiazp/action-set-secret@v1
      with:
        name: SQL_SERVER_ADMIN_USERNAME
        value: ${{ inputs.sql_server_admin_username }} 
        token: ${{ secrets.GIT_REPO_ACCESS_TOKEN }}
    - name: Set SQL Admin Password
      uses: jairandresdiazp/action-set-secret@v1
      with:
        name: SQL_SERVER_ADMIN_PASSWORD
        value: ${{ inputs.sql_server_admin_password }}
        token: ${{ secrets.GIT_REPO_ACCESS_TOKEN }}
        
  deploy_on_azure:
    name: Deploy on Azure
    runs-on: ubuntu-latest
    needs: set_action_secrets # Run only after successful completion of previous job
    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Checkout repository"
        uses: actions/checkout@main
      - name: "Deploy in Subscription scope"
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          region: 'westeurope'
          template: ./bicep/main.bicep
          # Overwrite values in .bicepparam with input parameters
          parameters: ./bicep/main.bicepparam application=${{ inputs.application }} sql_server_admin_username=${{ secrets.SQL_SERVER_ADMIN_USERNAME }} sql_server_admin_password=${{ secrets.SQL_SERVER_ADMIN_PASSWORD }}
          
  import_data_to_db:
    name: Import Data to SQL Database
    needs: deploy_on_azure
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Record Store App repository"
        uses: actions/checkout@main
        with:
          repository: MaryKroustali/record_store_app
          path: record_store_app
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.2.1
        with:
          connection-string: 'Server=tcp:sql-${{ inputs.application }}.database.windows.net,1433;Initial Catalog=chinook; User ID=${{ secrets.SQL_SERVER_ADMIN_USERNAME }}; Password=${{ secrets.SQL_SERVER_ADMIN_PASSWORD }}; Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
          path: record_store_app/SQL/chinook.sql
  
