name: Deploy

on:  # Trigger this workflow manually
  workflow_dispatch:
    inputs:
      location:
        description: 'Required. Deployment location'
        required: true
        default: 'westeurope'
      application:
        description: 'Optional. Overrides `application` parameter in main.bicepparam'
        required: true
        default: 'record-store'

permissions:
  id-token: write
  contents: read

jobs:
  deploy_on_azure:
    name: Deploy on Azure
    runs-on: ubuntu-latest
    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Checkout repository"
        uses: actions/checkout@main
      - name: "Deploy in Subscription scope"
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          region: ${{ inputs.location }}
          template: ./bicep/main.bicep
          parameters: ./bicep/main.bicepparam application=${{ inputs.application }}
          
  import_data_to_db:
    name: Import Data to SQL Database
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Record Store App repository"
        uses: actions/checkout@main
        with: 
          repository: MaryKroustali/record_store_app
          path: record_store_app
          
    
          

