name: Set Application Source Code

on:  # Trigger this workflow manually
  workflow_dispatch:
    inputs:
      application:
        description: 'Application Workload'
        required: true
        default: 'record-store'
      application_repo_url:
        description: 'Repository URL with Application Code'
        required: true
        default: 'https://github.com/MaryKroustali/record_store_app'
      application_repo_branch:
        description: 'Repository Branch with Application Code'
        required: true
        default: 'main'

permissions:
  id-token: write
      
jobs:
  webapp_source_config:
    name: Configure Source Code for WebApp
    runs-on: ubuntu-latest
    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Deploy Repository Code to Webapp"
        run: | 
          az webapp deployment source config --resource-group rg-${{ inputs.application }} --name app-${{ inputs.application }} --repository-type externalgit --repo-url ${{ inputs.application_repo_url }} --branch ${{ inputs.application_repo_branch }}          
